services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns_container
    ports:
      - "53:53/udp"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_container
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server
      - asa-server2
    networks:
      - asa-networks

  asa-server:
    build:
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server
    networks:
      - asa-networks
    # ports:
    #   - "8001:80/tcp"
  
  asa-server2:
    build:
      context: ./asa-server2
      dockerfile: Dockerfile
    container_name: asa-server2
    networks:
      - asa-networks
    # ports:
    #   - "8002:80/tcp"

networks:
  asa-networks:
    driver: bridge
