services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns_container
    ports:
      - "53:53/upd"

  proxy:
    build:
      context: ./prox
      dockerfile: Dockerfile
    container_name: proxy_container
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server
    networks:
      - asa-networks

  asa-server:
    build:
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server_container
    networks:
      asa-networks
  
  asa-server2:
    build:
      context: ./asa-server2
      dockerfile: Dockerfile
    container_name: asa-server_container2
    networks:
      asa-networks

networks:
  asa-networks:
    driver: bridge