services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns_container
    ports:
      - "53:53/upd"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_container
    ports:
      - "80:80/tcp"
