# web/Dockerfile
FROM nginx:latest
COPY default.conf /etc/nginx/conf.d
COPY home.html /usr/share/nginx/html/home.html
# COPY /home/endrew/computer_network/asa/asa-proxy-dns/asa-server/index.html /usr/share/nginx/html/index.html
# COPY /home/endrew/computer_network/asa/asa-proxy-dns/asa-server2/index.html /usr/share/nginx/html/index.html