# web/Dockerfile
FROM nginx:latest
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80
# COPY /home/endrew/computer_network/asa/asa-proxy-dns/proxy/home.html /usr/share/nginx/html/home.html
# COPY /home/endrew/computer_network/asa/asa-proxy-dns/asa-server/index.html /usr/share/nginx/html/index.html
